method: random
metric:
  goal: maximize
  name: CR
name: regularization
parameters:
  device:
    value: cuda
  weight_decay:
    distribution: log_uniform
    min: -7
    max: 0
  dropout:
    min: 0
    max: 0.3
  total_iters:
    1000